### ISSUE TITLE
Create .cbz or .cbr files

### ISSUE THREAD

**Issue by StrangeDOS** [omerap12/readComicOnline#2]
Create actual comic book files.  Example:  Download all the pages as .jpgs, then compress them into either a zip or rar file, then renaming it to <whatever the title and issue is>.cbz or .cbr

NOTE:  CBZ files are just zip files, CBR files are just rar files.

**Comment by omerap12** [comment]
done.

**Comment by StrangeDOS** [comment]
Awesome.  Check out Bug #3
