### ISSUE TITLE
Not enough padding

### ISSUE THREAD

**Issue by StrangeDOS** [omerap12/readComicOnline#3]
The tool doesn't pad out any extra digits.
<image>0.jpg
<image>1.jpg
<image>2.jpg
...and so on.  The problem with this is that when you put them into the .cbz/.cbr file, it messes up the order.  So instead of getting this..
<image>0.jpg
<image>1.jpg
<image>2.jpg
<image>3.jpg

...you end up getting them in this order when you read the comic file...
<image>0.jpg
<image>1.jpg
<image>10.jpg
<image>100.jpg

The way to resolve this is to pad out the numbers like this...
<image>00000.jpg
<image>00001.jpg
<image>00002.jpg
<image>00003.jpg

Then they will come out in order when you read them in any comic book reader.

NOTE:  I test with the Comicana reader but they all do the same thing.

**Comment by omerap12** [comment]
on it!

**Comment by omerap12** [comment]
Done.
