### ISSUE TITLE
Downloader creates an empty folder for an issue, then reports "Finished Downloading!"

### ISSUE THREAD

**Issue by deltz025** [omerap12/readComicOnline#6]
When using this script to download, a directory is created for every issue, but nothing is downloaded into it. 

First, the Progress window opens. Then, the Warning window opens with the message "using Threads: Please wait to complete download." Immediately after that, the Finished! window opens, and upon acknowledging both dialogs, the script closes. 

https://user-images.githubusercontent.com/49649081/208308683-a2a3d065-aa67-4917-9b1e-b1070e79be6e.mp4

**Comment by omerap12** [comment]
Thanks for letting me now, Ill check it out.
@deltz025 can you please send me the link you used in the video?

**Comment by StrangeDOS** [comment]
It looks like he used https://readcomiconline.li instead of https://readcomiconline.ru.  I don't know the difference between the .ru and .li domains.  They don't seem to be the same website.  I had the same problem when I tried to use the .li domain and had the same problem.

**Comment by omerap12** [comment]
As StrangeDos commented it's because of wrong url. 
I added some url validation to the code. hope it's enough. 
Thanks!
